testsuite_name = "OPFLOW Functionality"
application = 'opflow'
mpi_rank = 1
iterations = 1

[presets]
#netfile ='/nfs/gce/projects/ExaGO/exago_src/exago/datafiles/case9/case9mod.m'
netfile ='/nfs/gce/projects/ExaGO/exago_src/exago/datafiles/case_ACTIVSg2000.m'
print_output = 0

[[profiler]]

#[[profiler]]
#tool = 'nvprof'
#tool_args = '--profile-api-trace none --print-summary-per-gpu --log-file /nfs/gce/projects/ExaGO/auto_profiler/profiler_dumps/nvprofOutput'

#[[profiler]]
#tool = 'hpcrun'
#tool_args = '--disable-auditor -t -o /nfs/gce/projects/ExaGO/auto_profiler/profiler_dumps'
#
#[[profiler]]
#tool = 'tau_exec'
#tool_args = '-io'
#tool_envs = 'TAU_PROFILE=1 PROFILEDIR=/nfs/gce/projects/ExaGO/auto_profiler/profiler_dumps'

[[testcase]]
opflow_solver = 'HIOP'
hiop_compute_mode = 'GPU'
opflow_model = 'POWER_BALANCE_HIOP'
hiop_max_iter = 1

[[testcase]]
opflow_solver = 'IPOPT'
hiop_compute_mode = 'CPU'
opflow_model = 'POWER_BALANCE_POLAR'
ipopt_max_iter = 5
ipopt_print_level = 0

[[testcase]]
opflow_solver = 'HIOPSPARSE'
hiop_compute_mode = 'CPU'
hiop_max_iter = 5
hiop_verbosity_level = 0
opflow_model = 'POWER_BALANCE_POLAR'


