testsuite_name = "SCOPFLOW Functionality"
application = "scopflow"
mpi_rank = 1
iterations = 1

[presets]
netfile = '../datafiles/case_ACTIVSg200.m'
ctgcfile = '../datafiles/case_ACTIVSg200.cont'
scopflow_mode = 1
scopflow_Nc = 3
hiop_verbosity_level = 0
print_output = 0

[[profiler]]

[[profiler]]
tool = 'hpcrun'
tool_args = '--disable-auditor -t -o /nfs/gce/projects/ExaGO/auto_profiler/profiler_dumps'

[[profiler]]
tool = 'tau_exec'
tool_args = '-io'
tool_envs = 'TAU_PROFILE=1 PROFILEDIR=/nfs/gce/projects/ExaGO/auto_profiler/profiler_dumps'

[[profiler]]
tool = 'nvprof'
tool_args = '--log-file /nfs/gce/projects/ExaGO/auto_profiler/profiler_dumps/nvprofOutput'

[[testcase]]
scopflow_solver = 'IPOPT'
hiop_compute_mode = 'CPU'
scopflow_subproblem_model = 'POWER_BALANCE_POLAR'
scopflow_subproblem_solver = 'IPOPT'

[[testcase]]
scopflow_solver = 'EMPAR'
hiop_compute_mode = 'CPU'
scopflow_subproblem_model = 'POWER_BALANCE_POLAR'
scopflow_subproblem_solver = 'IPOPT'

[[testcase]]
scopflow_solver = 'EMPAR'
hiop_compute_mode = 'CPU'
scopflow_subproblem_model = 'POWER_BALANCE_POLAR'
scopflow_subproblem_solver = 'HIOPSPARSE'
